# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/UART_FIFO/UART_FIFO.xci
# IP: The module: 'UART_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/UART_FIFO/UART_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/UART_FIFO/UART_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/UART_FIFO/UART_FIFO.xci
# IP: The module: 'UART_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/UART_FIFO/UART_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/UART_FIFO/UART_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
