# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/clk_50M/clk_50M.xci
# IP: The module: 'clk_50M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/clk_50M/clk_50M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/clk_50M/clk_50M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/clk_50M/clk_50M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/clk_50M/clk_50M.xci
# IP: The module: 'clk_50M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/clk_50M/clk_50M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/clk_50M/clk_50M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Study/Xlinx/FPGA/uart/uart.srcs/sources_1/ip/clk_50M/clk_50M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
