set_property SRC_FILE_INFO {cfile:D:/Study/Xlinx/FPGA/uart/uart.srcs/constrs_1/new/top_uart.xdc rfile:../../../uart.srcs/constrs_1/new/top_uart.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports i_uart_rx]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports i_clk]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports o_uart_tx]
