######################################################################
#
# File name : SIM_uart_drive_TB.udo
# Created on: Fri Jul 14 10:10:40 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
