######################################################################
#
# File name : SIM_uart_drive_TB_compile.do
# Created on: Thu Aug 10 17:31:03 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\SoftWare\\Modelsim\\win64\\vlib modelsim_lib/work
D:\\SoftWare\\Modelsim\\win64\\vlib modelsim_lib/msim

D:\\SoftWare\\Modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\SoftWare\\Modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\SoftWare\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../uart.srcs/sources_1/ip/clk_50M" \
"../../../../uart.srcs/sources_1/new/clk_dev.v" \
"../../../../uart.srcs/sources_1/new/rst_gen.v" \
"../../../../uart.srcs/sources_1/new/uart_drive.v" \
"../../../../uart.srcs/sources_1/new/uart_rx.v" \
"../../../../uart.srcs/sources_1/new/uart_tx.v" \
"../../../../uart.srcs/sim_1/new/SIM_uart_drive_TB.v" \


# compile glbl module
D:\\SoftWare\\Modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

