######################################################################
#
# File name : SIM_uart_drive_TB_simulate.do
# Created on: Thu Aug 10 17:31:05 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.SIM_uart_drive_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {SIM_uart_drive_TB_wave.do}

view wave
view structure
view signals

do {SIM_uart_drive_TB.udo}

run 1000ns
